# Load the raw .csv file

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\vs_code\project_1\Luxury_Housing_Bangalore.csv")

df.head(1)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!

In [3]:
house = df.copy()

house.head(1)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!

In [4]:
house.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [5]:
house.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [6]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

# data cleaning

## drop duplicated

In [7]:
house[house.duplicated()]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100000,PROP036224,DOMLUR,Project_223,Embassy,4608.0,5bhk+,6.567529360287568,Secondary,HNI,2024-09-30,8.810723,8.286767,Launch,Broker,yes,9.291593,74,NaN
100001,PROP018298,Domlur,Project_297,Tata Housing,7455.0,5BHK+,NaN,Primary,Other,2024-12-31,4.173285,8.759681,Launch,Online,yes,8.447694,28,Great view from 15th floor.
100002,PROP084496,rajajinagar,Project_495,Prestige,3778.0,4bhk,12.568326856995945,Secondary,NRI,2023-12-31,9.366757,9.049776,Under construction,Broker,no,9.806097,92,Excellent location!
100003,PROP065620,DOMLUR,Project_119,Brigade,NaN,4BHK,₹12.59 Cr,Secondary,Startup Founder,2024-12-31,7.266646,5.718584,Launch,NRI Desk,yes,5.206301,88,Too far from my office.
100004,PROP088229,WHITEFIELD,Project_228,Total Environment,7458.0,4BHK,13.713149406825654,Secondary,HNI,2023-09-30,7.539427,7.310738,Ready to move,Direct,yes,6.533569,69,Connectivity is poor.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [8]:
house.drop_duplicates(inplace = True)

In [9]:
house

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193494537184,Primary,NRI,2023-12-31,8.379908,NaN,Under construction,Online,yes,8.378800,109,Underpriced for location.
99996,PROP099997,YELAHANKA,Project_496,L&T Realty,3171.0,4Bhk,12.272080796959921,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.
99997,PROP099998,rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730178633219271,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,NaN
99998,PROP099999,INDIRANAGAR,Project_498,SNN Raj,7342.0,4bhk,10.363988981166342,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,NaN
99999,PROP100000,hennur road,Project_499,Embassy,5016.0,5Bhk+,10.415616832095246,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,NaN

In [10]:
house.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

## drop unwanted columns

In [11]:
house = house.drop(['Property_ID'], axis= 1)

house

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,bellary road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193494537184,Primary,NRI,2023-12-31,8.379908,NaN,Under construction,Online,yes,8.378800,109,Underpriced for location.
99996,YELAHANKA,Project_496,L&T Realty,3171.0,4Bhk,12.272080796959921,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.
99997,rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730178633219271,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,NaN
99998,INDIRANAGAR,Project_498,SNN Raj,7342.0,4bhk,10.363988981166342,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,NaN
99999,hennur road,Project_499,Embassy,5016.0,5Bhk+,10.415616832095246,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,NaN

In [12]:
house = house.drop(['Buyer_Comments'], axis=1)

house

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min
0,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18
1,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106
2,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113
3,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106
4,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,bellary road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193494537184,Primary,NRI,2023-12-31,8.379908,NaN,Under construction,Online,yes,8.378800,109
99996,YELAHANKA,Project_496,L&T Realty,3171.0,4Bhk,12.272080796959921,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20
99997,rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730178633219271,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63
99998,INDIRANAGAR,Project_498,SNN Raj,7342.0,4bhk,10.363988981166342,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89
99999,hennur road,Project_499,Embassy,5016.0,5Bhk+,10.415616832095246,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95

## Clean inconsistent formats

In [13]:

house["Ticket_Price_Cr"] = (
    house["Ticket_Price_Cr"]
    .str.replace(" Cr", "", regex=False)   # remove "Cr"
    .str.replace("₹", "", regex=False)     # remove "₹"
    .str.strip()                           # remove spaces
)


house["Ticket_Price_Cr"] = pd.to_numeric(house["Ticket_Price_Cr"], errors="coerce")

house["Ticket_Price_Cr"]

0        12.750846
1        16.292152
2        10.517724
3         9.396367
4        15.345392
           ...
99995    10.185193
99996    12.272081
99997    13.730179
99998    10.363989
99999    10.415617
Name: Ticket_Price_Cr, Length: 100000, dtype: float64

In [14]:
house["Ticket_Price_Cr"].dtype

dtype('float64')

## spelling mistakes

In [15]:
house['Configuration'].unique()

array(['4bhk', '3Bhk', '3BHK', '4Bhk', '5BHK+', '4BHK', '5bhk+', '5Bhk+',
       '3bhk'], dtype=object)

In [16]:
house['Configuration'] = house['Configuration'].replace('4bhk','4BHK')
house['Configuration'] = house['Configuration'].replace('3Bhk','3BHK')
house['Configuration'] = house['Configuration'].replace('4Bhk','4BHK')
house['Configuration'] = house['Configuration'].replace('5bhk+','5BHK+')
house['Configuration'] = house['Configuration'].replace('5Bhk+','5BHK+')
house['Configuration'] = house['Configuration'].replace('3bhk','3BHK')

In [17]:
house['Configuration'].unique()

array(['4BHK', '3BHK', '5BHK+'], dtype=object)

In [18]:
house['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [19]:
house['Micro_Market'] = house['Micro_Market'].replace('sarjapur road','Sarjapur Road')
house['Micro_Market'] = house['Micro_Market'].replace('SARJAPUR ROAD','Sarjapur Road')

house['Micro_Market'] = house['Micro_Market'].replace('indiranagar','Indiranagar')
house['Micro_Market'] = house['Micro_Market'].replace('INDIRANAGAR','Indiranagar')

house['Micro_Market'] = house['Micro_Market'].replace('BANNERGHATTA ROAD','Bannerghatta Road')
house['Micro_Market'] = house['Micro_Market'].replace('bannerghatta road','Bannerghatta Road')

house['Micro_Market'] = house['Micro_Market'].replace('BELLARY ROAD','Bellary Road')
house['Micro_Market'] = house['Micro_Market'].replace('bellary road','Bellary Road')

house['Micro_Market'] = house['Micro_Market'].replace('KORAMANGALA','Koramangala')
house['Micro_Market'] = house['Micro_Market'].replace('koramangala','Koramangala')


house['Micro_Market'] = house['Micro_Market'].replace('whitefield','Whitefield')
house['Micro_Market'] = house['Micro_Market'].replace('WHITEFIELD','Whitefield')


house['Micro_Market'] = house['Micro_Market'].replace('yelahanka','Yelahanka')
house['Micro_Market'] = house['Micro_Market'].replace('YELAHANKA','Yelahanka')


house['Micro_Market'] = house['Micro_Market'].replace('JP NAGAR','Jp Nagar')
house['Micro_Market'] = house['Micro_Market'].replace('jp nagar','Jp Nagar')

house['Micro_Market'] = house['Micro_Market'].replace('RAJAJINAGAR','Rajajinagar')
house['Micro_Market'] = house['Micro_Market'].replace('rajajinagar','Rajajinagar')

house['Micro_Market'] = house['Micro_Market'].replace('jayanagar','Jayanagar')
house['Micro_Market'] = house['Micro_Market'].replace('JAYANAGAR','Jayanagar')

house['Micro_Market'] = house['Micro_Market'].replace('DOMLUR','Domlur')
house['Micro_Market'] = house['Micro_Market'].replace('domlur','Domlur')

house['Micro_Market'] = house['Micro_Market'].replace('MG ROAD','Mg Road')
house['Micro_Market'] = house['Micro_Market'].replace('mg road','Mg Road')

house['Micro_Market'] = house['Micro_Market'].replace('HENNUR ROAD','Hennur Road')
house['Micro_Market'] = house['Micro_Market'].replace('hennur road','Hennur Road')

house['Micro_Market'] = house['Micro_Market'].replace('electronic city','Electronic City')
house['Micro_Market'] = house['Micro_Market'].replace('ELECTRONIC CITY','Electronic City')

house['Micro_Market'] = house['Micro_Market'].replace('HEBBAL','Hebbal')
house['Micro_Market'] = house['Micro_Market'].replace('hebbal','Hebbal')

house['Micro_Market'] = house['Micro_Market'].replace('kanakapura road','Kanakapura Road')
house['Micro_Market'] = house['Micro_Market'].replace('KANAKAPURA ROAD','Kanakapura Road')

In [20]:
house['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'Bellary Road', 'Koramangala', 'Yelahanka', 'Whitefield',
       'Jp Nagar', 'Rajajinagar', 'Jayanagar', 'Domlur', 'Mg Road',
       'Hennur Road', 'Electronic City', 'Hebbal', 'Kanakapura Road'],
      dtype=object)

## Handle nulls in Unit_Size_Sqft, Ticket_Price_Cr, Amenity_Score

In [21]:
house.isnull().sum()

Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           9957
Configuration               0
Ticket_Price_Cr          9913
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
dtype: int64

In [22]:
house[house['Unit_Size_Sqft'].isnull()]

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min
17,Yelahanka,Project_17,L&T Realty,NaN,4BHK,9.045290,Secondary,CXO,2024-03-31,8.793448,5.186328,Ready to move,NRI Desk,yes,9.256085,77
18,Yelahanka,Project_18,Total Environment,NaN,5BHK+,7.623657,Primary,Other,2024-12-31,6.111031,6.898634,Ready to move,Broker,yes,8.652232,118
24,Mg Road,Project_24,L&T Realty,NaN,3BHK,13.640000,Primary,Other,2024-03-31,9.300782,9.464122,Under construction,Online,no,8.127972,43
33,Jp Nagar,Project_33,Tata Housing,NaN,5BHK+,15.018780,Primary,CXO,2024-09-30,7.991544,5.489478,Ready to move,Direct,yes,6.337526,64
45,Mg Road,Project_45,Brigade,NaN,5BHK+,15.671783,Primary,NRI,2023-12-31,8.186105,9.515085,Launch,NRI Desk,yes,5.414198,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99942,Bellary Road,Project_442,SNN Raj,NaN,3BHK,13.870145,Secondary,Other,2025-03-31,6.407603,7.377709,Launch,Broker,no,5.639231,41
99951,Whitefield,Project_451,Prestige,NaN,3BHK,11.783487,Secondary,HNI,2024-03-31,7.262669,5.038248,Ready to move,Broker,yes,8.992345,115
99957,Sarjapur Road,Project_457,Sobha,NaN,5BHK+,10.431024,Primary,NRI,2024-03-31,4.369459,6.544910,Ready to move,Direct,no,8.868635,61
99972,Bannerghatta Road,Project_472,SNN Raj,NaN,5BHK+,11.512373,Primary,NRI,2023-06-30,4.857654,6.766822,Ready to move,Broker,no,8.563902,19
99976,Hennur Road,Project_476,Brigade,NaN,4BHK,9.011187,Secondary,Startup Founder,2023-12-31,5.493179,5.909716,Ready to move,NRI Desk,no,9.005722,83

In [23]:
house.groupby(['Configuration'])['Unit_Size_Sqft'].median()

Configuration
3BHK     5982.0
4BHK     5992.0
5BHK+    5995.0
Name: Unit_Size_Sqft, dtype: float64

In [24]:
def impute_Unit_Size_Sqft(row):

    if np.isnan(row['Unit_Size_Sqft']):

      if row['Configuration'] == "3BHK":

        return 5981.848326

      elif row['Configuration'] == "4BHK":
        return 5996.000000

      elif row['Configuration'] == "5BHK+":
        return 5988.000000
    else:
        return row['Unit_Size_Sqft']

house['Unit_Size_Sqft'] =  house.apply(impute_Unit_Size_Sqft, axis = 1)

In [25]:
house.isnull().sum()

Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr          9913
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
dtype: int64

In [26]:
house[house['Ticket_Price_Cr'].isnull()]

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min
26,Jayanagar,Project_26,Godrej,7366.0,5BHK+,NaN,Primary,Startup Founder,2023-06-30,7.350917,8.447686,Launch,NRI Desk,yes,9.032851,105
40,Koramangala,Project_40,Godrej,7987.0,3BHK,NaN,Primary,CXO,2023-09-30,6.981554,5.087539,Ready to move,Online,yes,7.197818,72
43,Electronic City,Project_43,SNN Raj,7659.0,3BHK,NaN,Secondary,NRI,2023-12-31,6.180085,7.565496,Ready to move,NRI Desk,no,5.365011,34
51,Hennur Road,Project_51,L&T Realty,3163.0,4BHK,NaN,Secondary,HNI,2023-12-31,6.697532,7.002979,Launch,Broker,yes,5.617320,56
53,Mg Road,Project_53,Sobha,7849.0,3BHK,NaN,Secondary,CXO,2025-03-31,8.480134,9.820831,Launch,Online,no,5.609900,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99947,Jayanagar,Project_447,Godrej,7225.0,3BHK,NaN,Secondary,CXO,2024-06-30,8.041240,6.535174,Ready to move,NRI Desk,yes,5.528741,82
99949,Bellary Road,Project_449,Puravankara,5385.0,3BHK,NaN,Secondary,NRI,2023-09-30,9.671338,NaN,Launch,NRI Desk,yes,5.880172,29
99952,Whitefield,Project_452,Puravankara,4526.0,3BHK,NaN,Primary,NRI,2024-09-30,7.990770,NaN,Ready to move,Broker,yes,5.081095,16
99979,Sarjapur Road,Project_479,Brigade,5721.0,4BHK,NaN,Primary,Other,2024-06-30,6.666635,NaN,Ready to move,Online,yes,8.673101,32
99981,Koramangala,Project_481,Prestige,5301.0,4BHK,NaN,Primary,Other,2024-03-31,8.765275,7.552241,Launch,Direct,no,6.292689,76

In [27]:
house.groupby(['Configuration'])['Ticket_Price_Cr'].mean()

Configuration
3BHK     12.662261
4BHK     12.749241
5BHK+    12.745952
Name: Ticket_Price_Cr, dtype: float64

In [28]:
def impute_Ticket_Price_Cr(row):

    if np.isnan(row['Ticket_Price_Cr']):

      if row['Configuration'] == "3BHK":

        return 12.662261

      elif row['Configuration'] == "4BHK":
        return 12.749241

      elif row['Configuration'] == "5BHK+":
        return 12.745952
    else:
        return row['Ticket_Price_Cr']

house['Ticket_Price_Cr'] =  house.apply(impute_Ticket_Price_Cr, axis = 1)

In [29]:
house.isnull().sum()

Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
dtype: int64

In [30]:
house[house['Amenity_Score'].isnull()]

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min
1,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106
5,Yelahanka,Project_5,Brigade,4290.0,4BHK,9.820000,Secondary,HNI,2023-09-30,7.936068,NaN,Launch,Online,no,5.154027,16
10,Rajajinagar,Project_10,Godrej,8872.0,4BHK,15.221824,Secondary,CXO,2024-06-30,8.518025,NaN,Launch,Online,no,9.282135,102
15,Whitefield,Project_15,L&T Realty,4814.0,4BHK,70.000000,Primary,NRI,2024-03-31,9.401200,NaN,Under construction,Direct,no,9.850165,33
31,Hebbal,Project_31,Tata Housing,5228.0,5BHK+,12.211532,Secondary,HNI,2023-12-31,4.989089,NaN,Launch,Direct,no,8.878640,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99950,Koramangala,Project_450,RMZ,3258.0,5BHK+,8.417789,Primary,Other,2024-06-30,6.705624,NaN,Launch,NRI Desk,no,5.062150,59
99952,Whitefield,Project_452,Puravankara,4526.0,3BHK,12.662261,Primary,NRI,2024-09-30,7.990770,NaN,Ready to move,Broker,yes,5.081095,16
99979,Sarjapur Road,Project_479,Brigade,5721.0,4BHK,12.749241,Primary,Other,2024-06-30,6.666635,NaN,Ready to move,Online,yes,8.673101,32
99992,Domlur,Project_492,RMZ,6831.0,3BHK,19.257859,Primary,CXO,2023-12-31,6.065373,NaN,Ready to move,Online,yes,7.792512,25
99995,Bellary Road,Project_495,L&T Realty,5550.0,5BHK+,10.185193,Primary,NRI,2023-12-31,8.379908,NaN,Under construction,Online,yes,8.378800,109

In [31]:
house.groupby('Configuration')['Amenity_Score'].mean()

Configuration
3BHK     7.494281
4BHK     7.504818
5BHK+    7.513385
Name: Amenity_Score, dtype: float64

In [32]:
house.groupby('Configuration')['Amenity_Score'].median()

Configuration
3BHK     7.484899
4BHK     7.502260
5BHK+    7.514189
Name: Amenity_Score, dtype: float64

In [33]:
house.groupby('Developer_Name')['Amenity_Score'].median()

Developer_Name
Brigade              7.486064
Embassy              7.481968
Godrej               7.545401
L&T Realty           7.516065
Prestige             7.482133
Puravankara          7.458331
RMZ                  7.491426
SNN Raj              7.520361
Sobha                7.527468
Tata Housing         7.494180
Total Environment    7.514738
Name: Amenity_Score, dtype: float64

In [34]:
def impute_Amenity_Score(row):

    if np.isnan(row['Amenity_Score']):

      if row['Developer_Name'] == "Brigade":
        return 7.486064

      elif row['Developer_Name'] == "Embassy":
        return 7.481968

      elif row['Developer_Name'] == "Godrej":
        return 7.545401
    
      elif row['Developer_Name'] == "L&T Realty":
        return 7.516065

      elif row['Developer_Name'] == "Prestige":
        return 7.482133

      elif row['Developer_Name'] == "Puravankara":
        return 7.458331
    
      elif row['Developer_Name'] == "RMZ":
        return 7.491426

      elif row['Developer_Name'] == "SNN Raj":
        return 7.520361
    
      elif row['Developer_Name'] == "Sobha":
        return 7.527468

      elif row['Developer_Name'] == "Tata Housing":
        return 7.494180

      elif row['Developer_Name'] == "Total Environment":
        return 7.514738
    
    else:
        return row['Amenity_Score']

house['Amenity_Score'] =  house.apply(impute_Amenity_Score, axis = 1)

In [35]:
house.isnull().sum()

Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
dtype: int64

## dtype change

In [36]:
house.head()

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min
0,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18
1,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.458331,Under construction,NRI Desk,no,7.723898,106
2,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113
3,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106
4,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18

In [37]:
house.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Micro_Market          100000 non-null  object
 1   Project_Name          100000 non-null  object
 2   Developer_Name        100000 non-null  object
 3   Unit_Size_Sqft        100000 non-null  float64
 4   Configuration         100000 non-null  object
 5   Ticket_Price_Cr       100000 non-null  float64
 6   Transaction_Type      100000 non-null  object
 7   Buyer_Type            100000 non-null  object
 8   Purchase_Quarter      100000 non-null  object
 9   Connectivity_Score    100000 non-null  float64
 10  Amenity_Score         100000 non-null  float64
 11  Possession_Status     100000 non-null  object
 12  Sales_Channel         100000 non-null  object
 13  NRI_Buyer             100000 non-null  object
 14  Locality_Infra_Score  100000 non-null  float64
 15  Avg_Traffic_Time_Min  100000 non-null  int64
dtypes: float64(5), int64(1), object(10)
memory usage: 13.0+ MB

In [38]:
house['Purchase_Quarter'] = pd.to_datetime(house['Purchase_Quarter'])

In [39]:
house.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Micro_Market          100000 non-null  object
 1   Project_Name          100000 non-null  object
 2   Developer_Name        100000 non-null  object
 3   Unit_Size_Sqft        100000 non-null  float64
 4   Configuration         100000 non-null  object
 5   Ticket_Price_Cr       100000 non-null  float64
 6   Transaction_Type      100000 non-null  object
 7   Buyer_Type            100000 non-null  object
 8   Purchase_Quarter      100000 non-null  datetime64[ns]
 9   Connectivity_Score    100000 non-null  float64
 10  Amenity_Score         100000 non-null  float64
 11  Possession_Status     100000 non-null  object
 12  Sales_Channel         100000 non-null  object
 13  NRI_Buyer             100000 non-null  object
 14  Locality_Infra_Score  100000 non-null  float64
 15  Avg_Traffic_Time_Min  100000 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 13.0+ MB

# Derive columns like Price_per_Sqft, Quarter_Number, Booking_Flag

## Price_per_Sqft

In [40]:
house['Price_per_Sqft'] = (house['Ticket_Price_Cr'] * 10000000) / house['Unit_Size_Sqft']

In [41]:
house.shape

(100000, 17)

In [42]:
house.head()

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft
0,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.120594
1,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.458331,Under construction,NRI Desk,no,7.723898,106,28284.985887
2,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,13646.976013
3,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,15175.012103
4,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,21471.096187

## Quarter_Number

In [43]:
house['Quarter_Number'] = house['Purchase_Quarter'].dt.quarter

In [44]:
house.head(1)

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter_Number
0,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.120594,1

## Booking_Flag

In [45]:
house['Booking_Status'] = house['Transaction_Type'].apply(lambda x: 1 if x == 'Primary' else 0)

In [46]:
house['Purchase_Quarter'] = pd.to_datetime(house['Purchase_Quarter'])


house['Year'] = house['Purchase_Quarter'].dt.year



house['Year_Quarter'] = house['Purchase_Quarter'].dt.to_period('Q')

print(house)

            Micro_Market Project_Name Developer_Name  Unit_Size_Sqft  \
0          Sarjapur Road    Project_0            RMZ          4025.0
1            Indiranagar    Project_1    Puravankara          5760.0
2      Bannerghatta Road    Project_2   Tata Housing          7707.0
3           Bellary Road    Project_3        Embassy          6192.0
4            Koramangala    Project_4        SNN Raj          7147.0
...                  ...          ...            ...             ...
99995       Bellary Road  Project_495     L&T Realty          5550.0
99996          Yelahanka  Project_496     L&T Realty          3171.0
99997        Rajajinagar  Project_497       Prestige          5599.0
99998        Indiranagar  Project_498        SNN Raj          7342.0
99999        Hennur Road  Project_499        Embassy          5016.0

      Configuration  Ticket_Price_Cr Transaction_Type       Buyer_Type  \
0              4BHK        12.750846          Primary              NRI
1              3BHK        16.292152          Primary            Other
2              4BHK        10.517724          Primary              HNI
3              3BHK         9.396367          Primary              HNI
4              4BHK        15.345392        Secondary              HNI
...             ...              ...              ...              ...
99995         5BHK+        10.185193          Primary              NRI
99996          4BHK        12.272081        Secondary            Other
99997          4BHK        13.730179          Primary  Startup Founder
99998          4BHK        10.363989          Primary              NRI
99999         5BHK+        10.415617          Primary  Startup Founder

      Purchase_Quarter  Connectivity_Score  ...   Possession_Status  \
0           2025-03-31            7.990091  ...              Launch
1           2024-06-30            4.839024  ...  Under construction
2           2023-12-31            8.131315  ...       Ready to move
3           2024-03-31            7.501657  ...       Ready to move
4           2024-12-31            4.525216  ...  Under construction
...                ...                 ...  ...                 ...
99995       2023-12-31            8.379908  ...  Under construction
99996       2023-12-31            4.716304  ...              Launch
99997       2023-09-30            6.193347  ...              Launch
99998       2024-09-30            9.435646  ...  Under construction
99999       2024-09-30            5.786292  ...              Launch

      Sales_Channel NRI_Buyer Locality_Infra_Score  Avg_Traffic_Time_Min  \
0            Broker       yes             9.212491                    18
1          NRI Desk        no             7.723898                   106
2            Direct       yes             6.985493                   113
3            Online       yes             6.100929                   106
4            Broker        no             5.312510                    18
...             ...       ...                  ...                   ...
99995        Online       yes             8.378800                   109
99996        Broker       yes             7.025209                    20
99997      NRI Desk       yes             8.984990                    63
99998      NRI Desk       yes             7.634717                    89
99999        Broker       yes             6.039943                    95

       Price_per_Sqft  Quarter_Number  Booking_Status  Year  Year_Quarter
0        31679.120594               1               1  2025        2025Q1
1        28284.985887               2               1  2024        2024Q2
2        13646.976013               4               1  2023        2023Q4
3        15175.012103               1               1  2024        2024Q1
4        21471.096187               4               0  2024        2024Q4
...               ...             ...             ...   ...           ...
99995    18351.699990               4               1  2023        2023Q4
99996    38700.980123               4               0  2023        2023Q4
99997    24522.555158               3               1  2023        2023Q3
99998    14116.029667               3               1  2024        2024Q3
99999    20764.786348               3               1  2024        2024Q3

[100000 rows x 21 columns]

In [47]:
house

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,...,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter_Number,Booking_Status,Year,Year_Quarter
0,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,...,Launch,Broker,yes,9.212491,18,31679.120594,1,1,2025,2025Q1
1,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,...,Under construction,NRI Desk,no,7.723898,106,28284.985887,2,1,2024,2024Q2
2,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,...,Ready to move,Direct,yes,6.985493,113,13646.976013,4,1,2023,2023Q4
3,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,...,Ready to move,Online,yes,6.100929,106,15175.012103,1,1,2024,2024Q1
4,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,...,Under construction,Broker,no,5.312510,18,21471.096187,4,0,2024,2024Q4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Bellary Road,Project_495,L&T Realty,5550.0,5BHK+,10.185193,Primary,NRI,2023-12-31,8.379908,...,Under construction,Online,yes,8.378800,109,18351.699990,4,1,2023,2023Q4
99996,Yelahanka,Project_496,L&T Realty,3171.0,4BHK,12.272081,Secondary,Other,2023-12-31,4.716304,...,Launch,Broker,yes,7.025209,20,38700.980123,4,0,2023,2023Q4
99997,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,6.193347,...,Launch,NRI Desk,yes,8.984990,63,24522.555158,3,1,2023,2023Q3
99998,Indiranagar,Project_498,SNN Raj,7342.0,4BHK,10.363989,Primary,NRI,2024-09-30,9.435646,...,Under construction,NRI Desk,yes,7.634717,89,14116.029667,3,1,2024,2024Q3
99999,Hennur Road,Project_499,Embassy,5016.0,5BHK+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,...,Launch,Broker,yes,6.039943,95,20764.786348,3,1,2024,2024Q3

In [48]:
house['Locality_Infra_Score'].unique()

array([9.21249094, 7.72389833, 6.98549299, ..., 8.98499019, 7.63471681,
       6.03994292], shape=(100000,))

In [49]:
house.columns

Index(['Micro_Market', 'Project_Name', 'Developer_Name', 'Unit_Size_Sqft',
       'Configuration', 'Ticket_Price_Cr', 'Transaction_Type', 'Buyer_Type',
       'Purchase_Quarter', 'Connectivity_Score', 'Amenity_Score',
       'Possession_Status', 'Sales_Channel', 'NRI_Buyer',
       'Locality_Infra_Score', 'Avg_Traffic_Time_Min', 'Price_per_Sqft',
       'Quarter_Number', 'Booking_Status', 'Year', 'Year_Quarter'],
      dtype='object')

In [50]:
house.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Micro_Market          100000 non-null  object
 1   Project_Name          100000 non-null  object
 2   Developer_Name        100000 non-null  object
 3   Unit_Size_Sqft        100000 non-null  float64
 4   Configuration         100000 non-null  object
 5   Ticket_Price_Cr       100000 non-null  float64
 6   Transaction_Type      100000 non-null  object
 7   Buyer_Type            100000 non-null  object
 8   Purchase_Quarter      100000 non-null  datetime64[ns]
 9   Connectivity_Score    100000 non-null  float64
 10  Amenity_Score         100000 non-null  float64
 11  Possession_Status     100000 non-null  object
 12  Sales_Channel         100000 non-null  object
 13  NRI_Buyer             100000 non-null  object
 14  Locality_Infra_Score  100000 non-null  float64
 15  Avg_Traffic_Time_Min  100000 non-null  int64
 16  Price_per_Sqft        100000 non-null  float64
 17  Quarter_Number        100000 non-null  int32
 18  Booking_Status        100000 non-null  int64
 19  Year                  100000 non-null  int32
 20  Year_Quarter          100000 non-null  period[Q-DEC]
dtypes: datetime64[ns](1), float64(6), int32(2), int64(2), object(9), period[Q-DEC](1)
memory usage: 16.0+ MB

# save as csv file after data cleaning

In [51]:
house.to_csv("house_clean.csv", index=False)

# connect python(pandas) to SQL

In [52]:
! pip install psycopg2-binary sqlalchemy pandas python-dotenv

Requirement already satisfied: psycopg2-binary in .\lib\site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in .\lib\site-packages (2.0.42)
Requirement already satisfied: pandas in .\lib\site-packages (2.3.1)
Requirement already satisfied: python-dotenv in .\lib\site-packages (1.1.1)
Requirement already satisfied: greenlet>=1 in .\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in .\lib\site-packages (from sqlalchemy) (4.14.1)
Requirement already satisfied: numpy>=1.26.0 in .\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in .\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [53]:
import os
import psycopg2
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv

load_dotenv()

RENDER_DB_HOST = os.getenv("RENDER_DB_HOST")
RENDER_DB_NAME = os.getenv("RENDER_DB_NAME")
RENDER_DB_USER = os.getenv("RENDER_DB_USER")
RENDER_DB_PASSWORD = os.getenv("RENDER_DB_PASSWORD")
RENDER_DB_PORT = os.getenv("RENDER_DB_PORT")

# Connection string
DB_CONFIG = {
    'host': RENDER_DB_HOST,
    'dbname': RENDER_DB_NAME,
    'user': RENDER_DB_USER,
    'password': RENDER_DB_PASSWORD,
    'port': RENDER_DB_PORT
}

# Test psycopg2 connection
try:
    conn = psycopg2.connect(**DB_CONFIG)
    cursor = conn.cursor()
    cursor.execute("SELECT version();")
    print("✅ PostgreSQL Render connection successful!")
    print("Server version:", cursor.fetchone()[0])
    cursor.close()
    conn.close()
except Exception as e:
    print("❌ Error:", e)

✅ PostgreSQL Render connection successful!
Server version: PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

In [54]:
from sqlalchemy import create_engine, text

# Create engine
engine = create_engine(
    f"postgresql+psycopg2://{RENDER_DB_USER}:{RENDER_DB_PASSWORD}@{RENDER_DB_HOST}:{RENDER_DB_PORT}/{RENDER_DB_NAME}")

In [55]:
house["Year_Quarter"] = house["Year_Quarter"].astype(str)

In [57]:

house.to_sql(
    "luxury_house_data",
    engine,
    schema="public",
    if_exists="replace",
    index=False
)

print(pd.read_sql("SELECT * FROM luxury_house_data", engine))

            Micro_Market Project_Name Developer_Name  Unit_Size_Sqft  \
0          Sarjapur Road    Project_0            RMZ          4025.0
1            Indiranagar    Project_1    Puravankara          5760.0
2      Bannerghatta Road    Project_2   Tata Housing          7707.0
3           Bellary Road    Project_3        Embassy          6192.0
4            Koramangala    Project_4        SNN Raj          7147.0
...                  ...          ...            ...             ...
99995       Bellary Road  Project_495     L&T Realty          5550.0
99996          Yelahanka  Project_496     L&T Realty          3171.0
99997        Rajajinagar  Project_497       Prestige          5599.0
99998        Indiranagar  Project_498        SNN Raj          7342.0
99999        Hennur Road  Project_499        Embassy          5016.0

      Configuration  Ticket_Price_Cr Transaction_Type       Buyer_Type  \
0              4BHK        12.750846          Primary              NRI
1              3BHK        16.292152          Primary            Other
2              4BHK        10.517724          Primary              HNI
3              3BHK         9.396367          Primary              HNI
4              4BHK        15.345392        Secondary              HNI
...             ...              ...              ...              ...
99995         5BHK+        10.185193          Primary              NRI
99996          4BHK        12.272081        Secondary            Other
99997          4BHK        13.730179          Primary  Startup Founder
99998          4BHK        10.363989          Primary              NRI
99999         5BHK+        10.415617          Primary  Startup Founder

      Purchase_Quarter  Connectivity_Score  ...   Possession_Status  \
0           2025-03-31            7.990091  ...              Launch
1           2024-06-30            4.839024  ...  Under construction
2           2023-12-31            8.131315  ...       Ready to move
3           2024-03-31            7.501657  ...       Ready to move
4           2024-12-31            4.525216  ...  Under construction
...                ...                 ...  ...                 ...
99995       2023-12-31            8.379908  ...  Under construction
99996       2023-12-31            4.716304  ...              Launch
99997       2023-09-30            6.193347  ...              Launch
99998       2024-09-30            9.435646  ...  Under construction
99999       2024-09-30            5.786292  ...              Launch

      Sales_Channel NRI_Buyer Locality_Infra_Score  Avg_Traffic_Time_Min  \
0            Broker       yes             9.212491                    18
1          NRI Desk        no             7.723898                   106
2            Direct       yes             6.985493                   113
3            Online       yes             6.100929                   106
4            Broker        no             5.312510                    18
...             ...       ...                  ...                   ...
99995        Online       yes             8.378800                   109
99996        Broker       yes             7.025209                    20
99997      NRI Desk       yes             8.984990                    63
99998      NRI Desk       yes             7.634717                    89
99999        Broker       yes             6.039943                    95

       Price_per_Sqft  Quarter_Number  Booking_Status  Year  Year_Quarter
0        31679.120594               1               1  2025        2025Q1
1        28284.985887               2               1  2024        2024Q2
2        13646.976013               4               1  2023        2023Q4
3        15175.012103               1               1  2024        2024Q1
4        21471.096187               4               0  2024        2024Q4
...               ...             ...             ...   ...           ...
99995    18351.699990               4               1  2023        2023Q4
99996    38700.980123               4               0  2023        2023Q4
99997    24522.555158               3               1  2023        2023Q3
99998    14116.029667               3               1  2024        2024Q3
99999    20764.786348               3               1  2024        2024Q3

[100000 rows x 21 columns]

# Run initial SQL validation queries

## SELECT COUNT(*)

In [58]:
query = """
SELECT COUNT(*) AS total_row
FROM luxury_house_data;
"""

count = pd.read_sql(query, engine)
print(count)

   total_row
0     100000

## GROUP BY booking status

In [59]:
import pandas as pd

df_cols = pd.read_sql("SELECT * FROM luxury_house_data;", engine)
print(df_cols.columns)

Index(['Micro_Market', 'Project_Name', 'Developer_Name', 'Unit_Size_Sqft',
       'Configuration', 'Ticket_Price_Cr', 'Transaction_Type', 'Buyer_Type',
       'Purchase_Quarter', 'Connectivity_Score', 'Amenity_Score',
       'Possession_Status', 'Sales_Channel', 'NRI_Buyer',
       'Locality_Infra_Score', 'Avg_Traffic_Time_Min', 'Price_per_Sqft',
       'Quarter_Number', 'Booking_Status', 'Year', 'Year_Quarter'],
      dtype='object')

In [60]:
query = """
SELECT "Booking_Status", COUNT(*) AS total_per_status
FROM luxury_house_data
GROUP BY "Booking_Status";
"""
book_status = pd.read_sql(query, engine)
print(book_status)

   Booking_Status  total_per_status
0               0             49987
1               1             50013

## AVG ticket price per builder

In [61]:
query = """SELECT "Developer_Name", AVG("Ticket_Price_Cr") AS avg_ticket_price
FROM luxury_house_data
GROUP BY "Developer_Name"
ORDER BY avg_ticket_price DESC;
"""

avg_ticket = pd.read_sql(query, engine)
print(avg_ticket)

       Developer_Name  avg_ticket_price
0               Sobha         12.869719
1   Total Environment         12.815790
2          L&T Realty         12.783122
3              Godrej         12.761740
4         Puravankara         12.733261
5                 RMZ         12.728278
6            Prestige         12.721633
7        Tata Housing         12.666209
8             SNN Raj         12.624168
9             Embassy         12.605186
10            Brigade         12.603504

# 10th scenario

In [62]:
query = """
SELECT 
    "Developer_Name",
    SUM("Ticket_Price_Cr") AS Total_Revenue,
    COUNT(*) AS Total_Booked
FROM 
    luxury_house_data
WHERE 
    "Booking_Status" = 1
GROUP BY 
    "Developer_Name"
ORDER BY 
    Total_Revenue DESC
LIMIT 5;
"""

top5_builders = pd.read_sql(query, engine)
print(top5_builders)

  Developer_Name  total_revenue  total_booked
0       Prestige   59937.518762          4683
1     L&T Realty   59059.448872          4624
2          Sobha   58386.729286          4512
3            RMZ   58016.547304          4567
4        Brigade   58016.542387          4603